# shared/db/alembic/script.py.mako
"""add olympiad table

Revision ID: c828f03cadfe
Revises: 7d4a64c5d3a3
Create Date: 2025-11-25 08:18:37.436039

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = 'c828f03cadfe'
down_revision = '7d4a64c5d3a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('olympiad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('organizer', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('subjects', sa.JSON(), nullable=True),
    sa.Column('is_team', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('registration_deadline', sa.DateTime(), nullable=True),
    sa.Column('prize', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('parsed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_olympiad_content_hash'), 'olympiad', ['content_hash'], unique=False)
    op.create_index(op.f('ix_olympiad_is_active'), 'olympiad', ['is_active'], unique=False)
    op.create_index(op.f('ix_olympiad_registration_deadline'), 'olympiad', ['registration_deadline'], unique=False)
    op.create_index(op.f('ix_olympiad_slug'), 'olympiad', ['slug'], unique=True)
    op.create_index(op.f('ix_olympiad_title'), 'olympiad', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_olympiad_title'), table_name='olympiad')
    op.drop_index(op.f('ix_olympiad_slug'), table_name='olympiad')
    op.drop_index(op.f('ix_olympiad_registration_deadline'), table_name='olympiad')
    op.drop_index(op.f('ix_olympiad_is_active'), table_name='olympiad')
    op.drop_index(op.f('ix_olympiad_content_hash'), table_name='olympiad')
    op.drop_table('olympiad')
    # ### end Alembic commands ###